### ISSUE TITLE
acc.ini настройка

### ISSUE THREAD

**Issue by Otvertka72** [dzmuh97/HeroesWMBot#1]
Привет, хотел-бы уточнить, как правильно настроить поля botid, token, chat. Где их собственно получить? Спасибо.

**Comment by dzmuh97** [comment]
Привет. Проект делался, когда в ВК еще не было ботов в группах, потому предполагается, что botid - это id страницы (например vk.com/id1 - здесь id = 1), где ты хочешь запустить бота, token - access_token (vk.com/dev/first_guide пункт 3) от страницы с флагами messages и offline, а chat - CID диалога (например vk.com/im?sel=c557 - здесь CID = 557), где бот должен был отслеживать команды и куда присылал бы уведомления. К сожалению сейчас метод ВК API messages.get вырезали и вскоре вовсе отключат, потому бот "как есть" работать уже не будет. Проект делался для экспериментов и вряд ли будет поддерживаться, и я не уверен, что даже если изменить способ получения сообщений на LongPolling бот снова заработает (в виду возможных изменений в самой игре).

**Comment by Otvertka72** [comment]
Понял, спасибо большое за ответ. Успехов в новых проектах!)
